// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coreapiproje.Model;

namespace coreapiproje.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231019174419_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("coreapiproje.Model.Elemanlar", b =>
                {
                    b.Property<int>("elemanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("elemanAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("elemanCinsiyet")
                        .HasColumnType("bit");

                    b.Property<string>("elemanSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kiyafetID")
                        .HasColumnType("int");

                    b.HasKey("elemanID");

                    b.HasIndex("kiyafetID");

                    b.ToTable("elemanlars");
                });

            modelBuilder.Entity("coreapiproje.Model.Kiyafetler", b =>
                {
                    b.Property<int>("kiyafetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("kiyafetAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("magazaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("uretimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("uretimYeri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("kiyafetID");

                    b.HasIndex("magazaID");

                    b.ToTable("kiyafetlers");
                });

            modelBuilder.Entity("coreapiproje.Model.Magazalar", b =>
                {
                    b.Property<int>("magazaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("magazaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("magazaAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("magazaCalisanSayisi")
                        .HasColumnType("int");

                    b.HasKey("magazaID");

                    b.ToTable("magazalars");
                });

            modelBuilder.Entity("coreapiproje.Model.Müsteriler", b =>
                {
                    b.Property<int>("müsteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("elemanID")
                        .HasColumnType("int");

                    b.Property<string>("müsteriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("müsteriCinsiyet")
                        .HasColumnType("bit");

                    b.Property<DateTime>("müsteriDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("müsteriSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("müsteriID");

                    b.HasIndex("elemanID");

                    b.ToTable("müsterilers");
                });

            modelBuilder.Entity("coreapiproje.Model.Elemanlar", b =>
                {
                    b.HasOne("coreapiproje.Model.Kiyafetler", "kiyafetler")
                        .WithMany()
                        .HasForeignKey("kiyafetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kiyafetler");
                });

            modelBuilder.Entity("coreapiproje.Model.Kiyafetler", b =>
                {
                    b.HasOne("coreapiproje.Model.Magazalar", "magazalar")
                        .WithMany()
                        .HasForeignKey("magazaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("magazalar");
                });

            modelBuilder.Entity("coreapiproje.Model.Müsteriler", b =>
                {
                    b.HasOne("coreapiproje.Model.Elemanlar", "elemanlar")
                        .WithMany()
                        .HasForeignKey("elemanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("elemanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
